##
# docker-compose.yml
#
# ```
# $ alias dkc=docker-compose
# $ vi .env.default
# $ cp .env.default .env
# $ dkc config
# ```
#
# @license Apache-2.0
# @maintainer <github.com/farwish>
# @guide: https://docs.docker.com/compose/compose-file/
##

version: '3'
services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        NGINX_VERSION: ${IMG_NGINX_VERSION}
    container_name: nginx-con
    volumes:
      - ${DKC_AP}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${DKC_AP}/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ${DKC_AP}/nginx/cert:/etc/nginx/cert
      - ${DKC_AP}/web:${CONTAINER_WEB_AP}
      - /var/log/nginx/:/var/log/nginx/
    ports:
      - 80:80
      - 81:81
      - 443:443
    links:
      - php:php-address
    image: nginx-img-farwish:${IMG_NGINX_VERSION}

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
      args:
        MYSQL_VERSION: ${IMG_MYSQL_VERSION}
    container_name: mysql-con
    environment:                        # 相当于命令行中的环境变量 docker run -e KEY=VAL
      MYSQL_ROOT_PASSWORD: '123456'
    volumes:
      - /var/lib/docker/volumes/mysql:/var/lib/mysql
    ports:
      - ${HOST_MYSQL_PORT}:3306
    image: mysql-img-farwish:${IMG_MYSQL_VERSION}     # For tag

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
      args:
        REDIS_VERSION: ${IMG_REDIS_VERSION}
    container_name: redis-con
    volumes:
      - /var/lib/docker/volumes/redis:/data
    ports:
      - ${HOST_REDIS_PORT}:6379
    privileged: true
    sysctls:
      net.core.somaxconn: 1024
    image: redis-img-farwish:${IMG_REDIS_VERSION}

  php:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${IMG_PHP_VERSION}
    container_name: php-con
    volumes:
      - ${DKC_AP}/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ${DKC_AP}/php-fpm/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ${DKC_AP}/web:${CONTAINER_WEB_AP}
    ports:
      - ${HOST_PHP_PORT}:9000
    depends_on:
      - mysql
    image: php-img-farwish:${IMG_PHP_VERSION}

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${IMG_PHP_VERSION}
        WEB_PATH: ${CONTAINER_WEB_AP}
    container_name: web-con
    volumes:
      - ${DKC_AP}/web:${CONTAINER_WEB_AP}
    depends_on:
      - php
    image: web-img-farwish:${IMG_PHP_VERSION}

  fe:
    build:
      context: ./web
      dockerfile: Dockerfile-fe
      args:
        PHP_VERSION: ${IMG_PHP_VERSION}
        WEB_PATH: ${CONTAINER_WEB_AP}
    container_name: fe-con
    volumes:
      - ${DKC_AP}/web:${CONTAINER_WEB_AP}
    depends_on:
      - php
    image: fe-img-farwish:10.x

